services:
  app:
    build: .
    container_name: tourpoints_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    user: root
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload