"""agregar tabla auditoria poi_moderaciones

Revision ID: 5e0ac9f7b8ed
Revises: dd9d1878d96d
Create Date: 2026-07-16 14:59:31.204326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5e0ac9f7b8ed'
down_revision: Union[str, None] = 'dd9d1878d96d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# poi_estado_enum ya existe (creado en dd9d1878d96d); create_type=False evita que
# Alembic intente un CREATE TYPE duplicado al reutilizarlo aquí.
poi_estado_enum = postgresql.ENUM(
    'BORRADOR', 'PENDIENTE', 'APROBADO', 'RECHAZADO', 'INACTIVO',
    name='poi_estado_enum', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_moderaciones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('estado_anterior', poi_estado_enum, nullable=False),
    sa.Column('estado_nuevo', poi_estado_enum, nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_poi_moderaciones_poi', 'poi_moderaciones', ['poi_id'], unique=False)
    # NOTA: el autogenerate también detectó 'spatial_ref_sys' como tabla "eliminada" —
    # es una tabla del sistema de PostGIS (no un modelo nuestro), se omite a propósito
    # para no romper la extensión.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_poi_moderaciones_poi', table_name='poi_moderaciones')
    op.drop_table('poi_moderaciones')
    # ### end Alembic commands ###
