"""esquema inicial

Revision ID: dd9d1878d96d
Revises: 
Create Date: 2026-07-14 02:03:38.054124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2.types  # noqa: F401 -- necesario para el tipo Geography referenciado abajo

# revision identifiers, used by Alembic.
revision: str = 'dd9d1878d96d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensiones requeridas por el resto del esquema: pgcrypto para
    # gen_random_uuid(), postgis para los tipos GEOGRAPHY.
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "postgis"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_poi',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('icono', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insignias',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('icono', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('paises',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_iso', sa.CHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_iso')
    )
    op.create_table('reglas_puntos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('prioridad', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('configuracion', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vigencia_inicio', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('vigencia_fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('vigencia_fin IS NULL OR vigencia_inicio IS NULL OR vigencia_fin > vigencia_inicio'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reglas_puntos_configuracion', 'reglas_puntos', ['configuracion'], unique=False, postgresql_using='gin')
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('tipos_relacion_poi',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_jerarquica', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('es_bidireccional', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requiere_orden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['paises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rol_id', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'SUSPENDIDO', 'ELIMINADO', name='usuario_estado_enum'), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('configuracion', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ciudades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departamento_id', 'nombre')
    )
    op.create_table('conversaciones_ia',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='conversacion_role_enum'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('modelo', sa.String(length=80), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('temperatura', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=True),
    sa.Column('costo_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('finish_reason', sa.String(length=40), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversaciones_ia_session', 'conversaciones_ia', ['session_id', 'created_at'], unique=False)
    op.create_table('poi',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('categoria_id', sa.SmallInteger(), nullable=False),
    sa.Column('ciudad_id', sa.BigInteger(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.UUID(), nullable=True),
    sa.Column('fuente', sa.Enum('ADMIN', 'ESTABLECIMIENTO', 'USUARIO', 'IA', name='poi_fuente_enum'), server_default=sa.text("'ADMIN'"), nullable=False),
    sa.Column('nivel', sa.SmallInteger(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('radio_validacion', sa.SmallInteger(), server_default=sa.text('50'), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=True),
    sa.Column('sitio_web', sa.Text(), nullable=True),
    sa.Column('horarios', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'PENDIENTE', 'APROBADO', 'RECHAZADO', 'INACTIVO', name='poi_estado_enum'), server_default=sa.text("'BORRADOR'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_poi.id'], ),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_poi_categoria', 'poi', ['categoria_id'], unique=False)
    op.create_index('idx_poi_ciudad', 'poi', ['ciudad_id'], unique=False)
    op.create_index('idx_poi_created_at', 'poi', ['created_at'], unique=False)
    op.create_index('idx_poi_fuente', 'poi', ['fuente'], unique=False)
    op.create_index('idx_poi_horarios', 'poi', ['horarios'], unique=False, postgresql_using='gin')
    op.create_index('idx_poi_metadata', 'poi', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_poi_slug', 'poi', ['slug'], unique=False)
    op.create_index('idx_poi_ubicacion', 'poi', ['ubicacion'], unique=False, postgresql_using='gist')
    op.create_table('calificaciones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('calificacion', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calificacion BETWEEN 1 AND 5'),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'poi_id')
    )
    op.create_index('idx_calificaciones_poi', 'calificaciones', ['poi_id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='comentario_estado_enum'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comentarios_poi', 'comentarios', ['poi_id'], unique=False)
    op.create_index('idx_comentarios_usuario', 'comentarios', ['usuario_id'], unique=False)
    op.create_table('establecimientos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('tipo_negocio', sa.String(length=80), nullable=True),
    sa.Column('fecha_afiliacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'PENDIENTE', 'APROBADO', 'RECHAZADO', 'INACTIVO', name='poi_estado_enum'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit'),
    sa.UniqueConstraint('poi_id')
    )
    op.create_table('favoritos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'poi_id')
    )
    op.create_table('imagenes_poi',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('principal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poi_relaciones',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('poi_origen_id', sa.UUID(), nullable=False),
    sa.Column('poi_destino_id', sa.UUID(), nullable=False),
    sa.Column('tipo_relacion_id', sa.SmallInteger(), nullable=False),
    sa.Column('orden', sa.SmallInteger(), nullable=True),
    sa.Column('vigencia_inicio', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('vigencia_fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('poi_origen_id <> poi_destino_id'),
    sa.CheckConstraint('vigencia_fin IS NULL OR vigencia_fin > vigencia_inicio'),
    sa.ForeignKeyConstraint(['poi_destino_id'], ['poi.id'], ),
    sa.ForeignKeyConstraint(['poi_origen_id'], ['poi.id'], ),
    sa.ForeignKeyConstraint(['tipo_relacion_id'], ['tipos_relacion_poi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poi_origen_id', 'poi_destino_id', 'tipo_relacion_id')
    )
    op.create_index('idx_poi_relaciones_activo', 'poi_relaciones', ['activo'], unique=False, postgresql_where=sa.text('activo = true'))
    op.create_index('idx_poi_relaciones_destino', 'poi_relaciones', ['poi_destino_id'], unique=False)
    op.create_index('idx_poi_relaciones_origen', 'poi_relaciones', ['poi_origen_id'], unique=False)
    op.create_table('recompensas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'PENDIENTE', 'APROBADO', 'RECHAZADO', 'INACTIVO', name='poi_estado_enum'), server_default=sa.text("'BORRADOR'"), nullable=False),
    sa.CheckConstraint('puntos > 0'),
    sa.CheckConstraint('stock >= 0'),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.UUID(), nullable=False),
    sa.Column('ubicacion_usuario', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('precision_metros', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('distancia_metros', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('metodo_validacion', sa.Enum('GPS', 'QR', 'MIXTA', name='metodo_validacion_enum'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'VALIDADA', 'RECHAZADA', name='visita_estado_enum'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_visitas_ubicacion', 'visitas', ['ubicacion_usuario'], unique=False, postgresql_using='gist')
    op.create_table('compras',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('establecimiento_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('COP', 'USD', name='moneda_enum'), server_default=sa.text("'COP'"), nullable=False),
    sa.Column('codigo_transaccion', sa.String(length=60), nullable=True),
    sa.Column('estado', sa.Enum('REGISTRADA', 'CANCELADA', 'VALIDADA', name='compra_estado_enum'), server_default=sa.text("'REGISTRADA'"), nullable=False),
    sa.Column('cancelada_por', sa.UUID(), nullable=True),
    sa.Column('fecha_cancelacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(estado = 'CANCELADA' AND cancelada_por IS NOT NULL AND fecha_cancelacion IS NOT NULL) OR (estado <> 'CANCELADA' AND cancelada_por IS NULL AND fecha_cancelacion IS NULL)"),
    sa.CheckConstraint('valor > 0'),
    sa.ForeignKeyConstraint(['cancelada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_transaccion')
    )
    op.create_index('idx_compras_establecimiento', 'compras', ['establecimiento_id'], unique=False)
    op.create_index('idx_compras_usuario', 'compras', ['usuario_id'], unique=False)
    op.create_table('establecimiento_usuarios',
    sa.Column('establecimiento_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('establecimiento_id', 'usuario_id')
    )
    op.create_index('idx_establecimiento_usuarios_usuario', 'establecimiento_usuarios', ['usuario_id'], unique=False)
    op.create_table('promociones',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('establecimiento_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'PENDIENTE', 'APROBADO', 'RECHAZADO', 'INACTIVO', name='poi_estado_enum'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.CheckConstraint('fin > inicio'),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('VISITA', 'COMPRA', 'RECORRIDO', name='reto_tipo_enum'), nullable=False),
    sa.Column('recurrencia', sa.Enum('UNICA', 'DIARIA', 'SEMANAL', 'MENSUAL', name='reto_recurrencia_enum'), server_default=sa.text("'UNICA'"), nullable=False),
    sa.Column('cantidad_requerida', sa.SmallInteger(), nullable=False),
    sa.Column('recompensa_id', sa.UUID(), nullable=True),
    sa.Column('modo_recompensa', sa.Enum('GARANTIZADA', 'LIMITADA', 'SIN_RECOMPENSA', name='reto_modo_recompensa_enum'), server_default=sa.text("'SIN_RECOMPENSA'"), nullable=False),
    sa.Column('creado_por_usuario_id', sa.UUID(), nullable=True),
    sa.Column('establecimiento_id', sa.UUID(), nullable=True),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ACTIVO', 'FINALIZADO', 'CANCELADO', name='reto_estado_enum'), server_default=sa.text("'BORRADOR'"), nullable=False),
    sa.Column('configuracion', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("(modo_recompensa = 'SIN_RECOMPENSA' AND recompensa_id IS NULL) OR (modo_recompensa IN ('GARANTIZADA','LIMITADA') AND recompensa_id IS NOT NULL)"),
    sa.CheckConstraint('fin IS NULL OR fin > inicio'),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], ),
    sa.ForeignKeyConstraint(['recompensa_id'], ['recompensas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_retos_configuracion', 'retos', ['configuracion'], unique=False, postgresql_using='gin')
    op.create_index('idx_retos_establecimiento', 'retos', ['establecimiento_id'], unique=False, postgresql_where=sa.text('establecimiento_id IS NOT NULL'))
    op.create_index('idx_retos_recurrencia', 'retos', ['recurrencia'], unique=False, postgresql_where=sa.text("estado = 'ACTIVO'"))
    op.create_index('idx_retos_tipo_estado', 'retos', ['tipo', 'estado'], unique=False)
    op.create_table('hitos_racha',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('reto_id', sa.UUID(), nullable=False),
    sa.Column('racha_requerida', sa.SmallInteger(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('puntos_bonus', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('recompensa_id', sa.UUID(), nullable=True),
    sa.Column('insignia_id', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('puntos_bonus >= 0'),
    sa.CheckConstraint('racha_requerida > 0'),
    sa.ForeignKeyConstraint(['insignia_id'], ['insignias.id'], ),
    sa.ForeignKeyConstraint(['recompensa_id'], ['recompensas.id'], ),
    sa.ForeignKeyConstraint(['reto_id'], ['retos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reto_id', 'racha_requerida')
    )
    op.create_index('idx_hitos_racha_reto', 'hitos_racha', ['reto_id'], unique=False)
    op.create_table('rachas_retos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('reto_id', sa.UUID(), nullable=False),
    sa.Column('racha_actual', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('racha_maxima', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('ultimo_periodo_inicio', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ultimo_periodo_completado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('racha_actual >= 0 AND racha_maxima >= racha_actual'),
    sa.ForeignKeyConstraint(['reto_id'], ['retos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'reto_id')
    )
    op.create_index('idx_rachas_retos_usuario', 'rachas_retos', ['usuario_id', 'reto_id'], unique=False)
    op.create_table('usuario_retos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('reto_id', sa.UUID(), nullable=False),
    sa.Column('periodo_inicio', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('periodo_fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('numero_intento', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('progreso', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"completados": [], "cantidad": 0}\'::jsonb'), nullable=False),
    sa.Column('porcentaje', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('fecha_completado', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ACTIVO', 'FINALIZADO', 'CANCELADO', name='reto_estado_enum'), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('periodo_fin IS NULL OR periodo_fin > periodo_inicio'),
    sa.CheckConstraint('porcentaje BETWEEN 0 AND 100'),
    sa.ForeignKeyConstraint(['reto_id'], ['retos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'reto_id', 'periodo_inicio', 'numero_intento')
    )
    op.create_index('idx_usuario_retos_intento_activo', 'usuario_retos', ['usuario_id', 'reto_id', 'periodo_inicio'], unique=True, postgresql_where=sa.text("estado = 'ACTIVO'"))
    op.create_index('idx_usuario_retos_periodo', 'usuario_retos', ['reto_id', 'periodo_inicio'], unique=False)
    op.create_index('idx_usuario_retos_progreso', 'usuario_retos', ['progreso'], unique=False, postgresql_using='gin')
    op.create_table('canjes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('recompensa_id', sa.UUID(), nullable=False),
    sa.Column('origen', sa.Enum('PUNTOS', 'RETO', name='canje_origen_enum'), server_default=sa.text("'PUNTOS'"), nullable=False),
    sa.Column('usuario_reto_id', sa.UUID(), nullable=True),
    sa.Column('codigo_qr', sa.Text(), nullable=False),
    sa.Column('fecha_expira', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fecha_redencion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'REDIMIDO', 'EXPIRADO', name='canje_estado_enum'), server_default=sa.text("'PENDIENTE'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(origen = 'RETO' AND usuario_reto_id IS NOT NULL) OR (origen = 'PUNTOS' AND usuario_reto_id IS NULL)"),
    sa.ForeignKeyConstraint(['recompensa_id'], ['recompensas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_reto_id'], ['usuario_retos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_qr')
    )
    op.create_index('idx_canjes_origen', 'canjes', ['origen'], unique=False)
    op.create_index('idx_canjes_usuario_reto', 'canjes', ['usuario_reto_id'], unique=False, postgresql_where=sa.text('usuario_reto_id IS NOT NULL'))
    op.create_table('hitos_racha_alcanzados',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('hito_id', sa.UUID(), nullable=False),
    sa.Column('usuario_reto_id', sa.UUID(), nullable=False),
    sa.Column('recompensa_otorgada', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hito_id'], ['hitos_racha.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_reto_id'], ['usuario_retos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hitos_racha_alcanzados_usuario', 'hitos_racha_alcanzados', ['usuario_id', 'hito_id'], unique=False)
    op.create_table('sesiones_reto',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_reto_id', sa.UUID(), nullable=False),
    sa.Column('inicio', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fin', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'ACTIVO', 'FINALIZADO', 'CANCELADO', name='reto_estado_enum'), server_default=sa.text("'ACTIVO'"), nullable=False),
    sa.CheckConstraint('fin IS NULL OR fin > inicio'),
    sa.ForeignKeyConstraint(['usuario_reto_id'], ['usuario_retos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sesiones_reto_usuario_reto', 'sesiones_reto', ['usuario_reto_id'], unique=False)
    op.create_table('movimientos_puntos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('regla_id', sa.UUID(), nullable=True),
    sa.Column('visita_id', sa.UUID(), nullable=True),
    sa.Column('compra_id', sa.UUID(), nullable=True),
    sa.Column('usuario_reto_id', sa.UUID(), nullable=True),
    sa.Column('canje_id', sa.UUID(), nullable=True),
    sa.Column('tipo_movimiento', sa.Enum('VISITA', 'COMPRA', 'RETO', 'CANJE', name='tipo_movimiento_puntos_enum'), sa.Computed("\n            CASE\n                WHEN visita_id IS NOT NULL THEN 'VISITA'::tipo_movimiento_puntos_enum\n                WHEN compra_id IS NOT NULL THEN 'COMPRA'::tipo_movimiento_puntos_enum\n                WHEN usuario_reto_id IS NOT NULL THEN 'RETO'::tipo_movimiento_puntos_enum\n                WHEN canje_id IS NOT NULL THEN 'CANJE'::tipo_movimiento_puntos_enum\n            END\n            ", persisted=True), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(visita_id, compra_id, usuario_reto_id, canje_id) = 1'),
    sa.ForeignKeyConstraint(['canje_id'], ['canjes.id'], ),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['regla_id'], ['reglas_puntos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_reto_id'], ['usuario_retos.id'], ),
    sa.ForeignKeyConstraint(['visita_id'], ['visitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movimientos_puntos_tipo', 'movimientos_puntos', ['tipo_movimiento'], unique=False)
    op.create_index('idx_movimientos_puntos_usuario', 'movimientos_puntos', ['usuario_id'], unique=False)
    # ### end Alembic commands ###

    # --- Funciones, triggers y vistas (SQLAlchemy no las genera) ---
    # Réplica 1:1 de schem_posgrest.sql. Van después de crear las tablas
    # porque todas referencian columnas/tablas ya existentes.

    op.execute("""
        CREATE OR REPLACE FUNCTION fn_set_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_usuarios_updated_at
            BEFORE UPDATE ON usuarios
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    """)
    op.execute("""
        CREATE TRIGGER trg_poi_updated_at
            BEFORE UPDATE ON poi
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    """)
    op.execute("""
        CREATE TRIGGER trg_rachas_retos_updated_at
            BEFORE UPDATE ON rachas_retos
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION fn_actualizar_nivel_poi()
        RETURNS TRIGGER AS $$
        DECLARE
            v_destino_id  UUID;
            v_nuevo_nivel SMALLINT;
        BEGIN
            v_destino_id := COALESCE(NEW.poi_destino_id, OLD.poi_destino_id);

            SELECT MIN(COALESCE(p_origen.nivel, 0)) + 1
            INTO v_nuevo_nivel
            FROM poi_relaciones pr
            JOIN tipos_relacion_poi t ON t.id = pr.tipo_relacion_id
            JOIN poi p_origen ON p_origen.id = pr.poi_origen_id
            WHERE pr.poi_destino_id = v_destino_id
              AND t.es_jerarquica
              AND pr.activo;

            UPDATE poi SET nivel = v_nuevo_nivel WHERE id = v_destino_id;

            RETURN COALESCE(NEW, OLD);
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_actualizar_nivel_poi
            AFTER INSERT OR UPDATE OR DELETE ON poi_relaciones
            FOR EACH ROW EXECUTE FUNCTION fn_actualizar_nivel_poi();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION fn_otorgar_recompensa_hito()
        RETURNS TRIGGER AS $$
        DECLARE
            v_recompensa_id UUID;
            v_stock         INTEGER;
        BEGIN
            SELECT recompensa_id INTO v_recompensa_id
            FROM hitos_racha WHERE id = NEW.hito_id;

            IF v_recompensa_id IS NULL THEN
                NEW.recompensa_otorgada := false;
                RETURN NEW;
            END IF;

            SELECT stock INTO v_stock FROM recompensas WHERE id = v_recompensa_id FOR UPDATE;

            IF v_stock IS NOT NULL AND v_stock > 0 THEN
                UPDATE recompensas SET stock = stock - 1 WHERE id = v_recompensa_id;
                NEW.recompensa_otorgada := true;
            ELSE
                NEW.recompensa_otorgada := false;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_otorgar_recompensa_hito
            BEFORE INSERT ON hitos_racha_alcanzados
            FOR EACH ROW EXECUTE FUNCTION fn_otorgar_recompensa_hito();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION fn_reservar_o_bloquear_reto()
        RETURNS TRIGGER AS $$
        DECLARE
            v_recompensa_id UUID;
            v_modo          reto_modo_recompensa_enum;
            v_stock         INTEGER;
        BEGIN
            SELECT recompensa_id, modo_recompensa INTO v_recompensa_id, v_modo
            FROM retos WHERE id = NEW.reto_id;

            IF v_modo = 'GARANTIZADA' THEN
                SELECT stock INTO v_stock FROM recompensas WHERE id = v_recompensa_id FOR UPDATE;
                IF v_stock IS NULL OR v_stock <= 0 THEN
                    RAISE EXCEPTION 'Reto % está agotado (modo GARANTIZADA sin stock para reservar)', NEW.reto_id;
                END IF;
                UPDATE recompensas SET stock = stock - 1 WHERE id = v_recompensa_id;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_reservar_o_bloquear_reto
            BEFORE INSERT ON usuario_retos
            FOR EACH ROW EXECUTE FUNCTION fn_reservar_o_bloquear_reto();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION fn_liberar_reserva_si_no_completa()
        RETURNS TRIGGER AS $$
        DECLARE
            v_recompensa_id UUID;
            v_modo          reto_modo_recompensa_enum;
        BEGIN
            IF OLD.estado = 'ACTIVO' AND NEW.estado = 'CANCELADO' THEN
                SELECT recompensa_id, modo_recompensa INTO v_recompensa_id, v_modo
                FROM retos WHERE id = NEW.reto_id;

                IF v_modo = 'GARANTIZADA' AND v_recompensa_id IS NOT NULL THEN
                    UPDATE recompensas SET stock = stock + 1 WHERE id = v_recompensa_id;
                END IF;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_liberar_reserva_si_no_completa
            AFTER UPDATE ON usuario_retos
            FOR EACH ROW
            WHEN (OLD.estado IS DISTINCT FROM NEW.estado)
            EXECUTE FUNCTION fn_liberar_reserva_si_no_completa();
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION fn_expirar_retos_vencidos()
        RETURNS INTEGER AS $$
        DECLARE
            v_count INTEGER;
        BEGIN
            UPDATE usuario_retos
            SET estado = 'CANCELADO'
            WHERE estado = 'ACTIVO'
              AND periodo_fin IS NOT NULL
              AND periodo_fin < now();
            GET DIAGNOSTICS v_count = ROW_COUNT;
            RETURN v_count;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE OR REPLACE FUNCTION fn_descontar_stock_canje()
        RETURNS TRIGGER AS $$
        DECLARE
            v_stock INTEGER;
            v_modo  reto_modo_recompensa_enum;
        BEGIN
            IF NEW.origen = 'RETO' THEN
                SELECT r.modo_recompensa INTO v_modo
                FROM usuario_retos ur JOIN retos r ON r.id = ur.reto_id
                WHERE ur.id = NEW.usuario_reto_id;

                IF v_modo = 'GARANTIZADA' THEN
                    RETURN NEW;
                END IF;
            END IF;

            SELECT stock INTO v_stock FROM recompensas WHERE id = NEW.recompensa_id FOR UPDATE;
            IF v_stock IS NULL OR v_stock <= 0 THEN
                RAISE EXCEPTION 'Recompensa % agotada; no se puede generar el canje', NEW.recompensa_id;
            END IF;
            UPDATE recompensas SET stock = stock - 1 WHERE id = NEW.recompensa_id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_descontar_stock_canje
            BEFORE INSERT ON canjes
            FOR EACH ROW EXECUTE FUNCTION fn_descontar_stock_canje();
    """)

    op.execute("""
        CREATE VIEW retos_disponibilidad AS
        SELECT
            r.*,
            rec.stock AS stock_recompensa,
            CASE
                WHEN r.modo_recompensa = 'SIN_RECOMPENSA' THEN true
                WHEN r.modo_recompensa = 'LIMITADA' THEN true
                ELSE COALESCE(rec.stock, 0) > 0
            END AS disponible
        FROM retos r
        LEFT JOIN recompensas rec ON rec.id = r.recompensa_id;
    """)
    op.execute("""
        CREATE VIEW saldo_puntos_usuario AS
        SELECT usuario_id, SUM(puntos) AS saldo
        FROM movimientos_puntos
        GROUP BY usuario_id;
    """)


def downgrade() -> None:
    # --- Vistas, triggers y funciones primero (dependen de las tablas) ---
    op.execute("DROP VIEW IF EXISTS saldo_puntos_usuario")
    op.execute("DROP VIEW IF EXISTS retos_disponibilidad")
    op.execute("DROP TRIGGER IF EXISTS trg_descontar_stock_canje ON canjes")
    op.execute("DROP FUNCTION IF EXISTS fn_descontar_stock_canje()")
    op.execute("DROP FUNCTION IF EXISTS fn_expirar_retos_vencidos()")
    op.execute("DROP TRIGGER IF EXISTS trg_liberar_reserva_si_no_completa ON usuario_retos")
    op.execute("DROP FUNCTION IF EXISTS fn_liberar_reserva_si_no_completa()")
    op.execute("DROP TRIGGER IF EXISTS trg_reservar_o_bloquear_reto ON usuario_retos")
    op.execute("DROP FUNCTION IF EXISTS fn_reservar_o_bloquear_reto()")
    op.execute("DROP TRIGGER IF EXISTS trg_otorgar_recompensa_hito ON hitos_racha_alcanzados")
    op.execute("DROP FUNCTION IF EXISTS fn_otorgar_recompensa_hito()")
    op.execute("DROP TRIGGER IF EXISTS trg_actualizar_nivel_poi ON poi_relaciones")
    op.execute("DROP FUNCTION IF EXISTS fn_actualizar_nivel_poi()")
    op.execute("DROP TRIGGER IF EXISTS trg_rachas_retos_updated_at ON rachas_retos")
    op.execute("DROP TRIGGER IF EXISTS trg_poi_updated_at ON poi")
    op.execute("DROP TRIGGER IF EXISTS trg_usuarios_updated_at ON usuarios")
    op.execute("DROP FUNCTION IF EXISTS fn_set_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_movimientos_puntos_usuario', table_name='movimientos_puntos')
    op.drop_index('idx_movimientos_puntos_tipo', table_name='movimientos_puntos')
    op.drop_table('movimientos_puntos')
    op.drop_index('idx_sesiones_reto_usuario_reto', table_name='sesiones_reto')
    op.drop_table('sesiones_reto')
    op.drop_index('idx_hitos_racha_alcanzados_usuario', table_name='hitos_racha_alcanzados')
    op.drop_table('hitos_racha_alcanzados')
    op.drop_index('idx_canjes_usuario_reto', table_name='canjes', postgresql_where=sa.text('usuario_reto_id IS NOT NULL'))
    op.drop_index('idx_canjes_origen', table_name='canjes')
    op.drop_table('canjes')
    op.drop_index('idx_usuario_retos_progreso', table_name='usuario_retos', postgresql_using='gin')
    op.drop_index('idx_usuario_retos_periodo', table_name='usuario_retos')
    op.drop_index('idx_usuario_retos_intento_activo', table_name='usuario_retos', postgresql_where=sa.text("estado = 'ACTIVO'"))
    op.drop_table('usuario_retos')
    op.drop_index('idx_rachas_retos_usuario', table_name='rachas_retos')
    op.drop_table('rachas_retos')
    op.drop_index('idx_hitos_racha_reto', table_name='hitos_racha')
    op.drop_table('hitos_racha')
    op.drop_index('idx_retos_tipo_estado', table_name='retos')
    op.drop_index('idx_retos_recurrencia', table_name='retos', postgresql_where=sa.text("estado = 'ACTIVO'"))
    op.drop_index('idx_retos_establecimiento', table_name='retos', postgresql_where=sa.text('establecimiento_id IS NOT NULL'))
    op.drop_index('idx_retos_configuracion', table_name='retos', postgresql_using='gin')
    op.drop_table('retos')
    op.drop_table('promociones')
    op.drop_index('idx_establecimiento_usuarios_usuario', table_name='establecimiento_usuarios')
    op.drop_table('establecimiento_usuarios')
    op.drop_index('idx_compras_usuario', table_name='compras')
    op.drop_index('idx_compras_establecimiento', table_name='compras')
    op.drop_table('compras')
    op.drop_index('idx_visitas_ubicacion', table_name='visitas', postgresql_using='gist')
    op.drop_table('visitas')
    op.drop_table('recompensas')
    op.drop_index('idx_poi_relaciones_origen', table_name='poi_relaciones')
    op.drop_index('idx_poi_relaciones_destino', table_name='poi_relaciones')
    op.drop_index('idx_poi_relaciones_activo', table_name='poi_relaciones', postgresql_where=sa.text('activo = true'))
    op.drop_table('poi_relaciones')
    op.drop_table('imagenes_poi')
    op.drop_table('favoritos')
    op.drop_table('establecimientos')
    op.drop_index('idx_comentarios_usuario', table_name='comentarios')
    op.drop_index('idx_comentarios_poi', table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index('idx_calificaciones_poi', table_name='calificaciones')
    op.drop_table('calificaciones')
    op.drop_index('idx_poi_ubicacion', table_name='poi', postgresql_using='gist')
    op.drop_index('idx_poi_slug', table_name='poi')
    op.drop_index('idx_poi_metadata', table_name='poi', postgresql_using='gin')
    op.drop_index('idx_poi_horarios', table_name='poi', postgresql_using='gin')
    op.drop_index('idx_poi_fuente', table_name='poi')
    op.drop_index('idx_poi_created_at', table_name='poi')
    op.drop_index('idx_poi_ciudad', table_name='poi')
    op.drop_index('idx_poi_categoria', table_name='poi')
    op.drop_table('poi')
    op.drop_index('idx_conversaciones_ia_session', table_name='conversaciones_ia')
    op.drop_table('conversaciones_ia')
    op.drop_table('ciudades')
    op.drop_table('usuarios')
    op.drop_table('departamentos')
    op.drop_table('tipos_relacion_poi')
    op.drop_table('roles')
    op.drop_index('idx_reglas_puntos_configuracion', table_name='reglas_puntos', postgresql_using='gin')
    op.drop_table('reglas_puntos')
    op.drop_table('paises')
    op.drop_table('insignias')
    op.drop_table('categorias_poi')
    # ### end Alembic commands ###
